version: "3"
services:
  sc2elf:
    container_name: sc2elf
    build:
      context: .
    image: sc2elf:latest
    ports:
      - 0.0.0.0:31337:31337
    restart: always
    cap_drop:
      - FSETID
      - SETUID
      - SETGID
      - SYS_CHROOT
      - SYS_PTRACE
      - CHOWN
      - NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
      - NET_BIND_SERVICE
